# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 11:14
from __future__ import unicode_literals

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', accounts.models.CustomerUserManager()),
            ],
        ),
    ]
